# Generated by Django 2.2.4 on 2019-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('book', '0002_book_description'),
        ('user', '0003_auto_20190809_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', through='review.Review', to='book.Book'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='book.Book'),
        ),
    ]
