# Generated by Django 2.2.4 on 2019-08-21 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_book_description'),
        ('user', '0004_auto_20190817_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(max_length=5)),
                ('days_lended', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(21)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
            ],
        ),
    ]
