# Generated by Django 2.2.4 on 2019-08-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190821_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='days_lended',
        ),
    ]
