# Generated by Django 2.2.4 on 2019-08-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(upload_to='images/books/')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default=10)),
                ('avg_rating', models.FloatField(default=3)),
                ('publisher', models.CharField(max_length=200)),
                ('no_of_pages', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
