# Generated by Django 2.2.4 on 2019-08-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190809_0353'),
        ('review', '0001_initial'),
        ('book', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(through='review.Review', to='user.Customer'),
        ),
    ]
